-- =========================================================================
-- DEWA PORTFOLIO PRODUCT CONTENT TABLES
-- Target project: DewaProject / DewaPortoWeb
-- Instructions: run this in Supabase SQL Editor or through Supabase MCP.
-- =========================================================================

create table if not exists public.product_case_studies (
    id bigint generated by default as identity primary key,
    project_id bigint references public.projects(id) on delete set null,
    slug text not null unique,
    title text not null,
    category text not null,
    summary text not null,
    role text not null default '',
    timeline text not null default '',
    mode text not null default 'Learning & Next Improvement'
        check (mode in ('Outcome', 'Validation Outcome', 'Learning & Next Improvement')),
    visual text not null default '',
    context text not null default '',
    problem text not null default '',
    insight text not null default '',
    approach text not null default '',
    output text not null default '',
    outcome text not null default '',
    deliverables text[] not null default '{}',
    sort_order integer not null default 1,
    is_published boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.product_documents (
    id bigint generated by default as identity primary key,
    title text not null,
    type text not null default '',
    description text not null default '',
    file_path text,
    sort_order integer not null default 1,
    is_published boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists product_case_studies_published_sort_idx
on public.product_case_studies (is_published, sort_order, created_at desc);

create index if not exists product_case_studies_project_id_idx
on public.product_case_studies (project_id);

create index if not exists product_documents_published_sort_idx
on public.product_documents (is_published, sort_order, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists product_case_studies_set_updated_at on public.product_case_studies;
create trigger product_case_studies_set_updated_at
before update on public.product_case_studies
for each row execute function public.set_updated_at();

drop trigger if exists product_documents_set_updated_at on public.product_documents;
create trigger product_documents_set_updated_at
before update on public.product_documents
for each row execute function public.set_updated_at();

alter table public.product_case_studies enable row level security;
alter table public.product_documents enable row level security;

drop policy if exists "Enable public read access on product case studies" on public.product_case_studies;
drop policy if exists "Enable admin full access to product case studies" on public.product_case_studies;
drop policy if exists "Enable public read access on product documents" on public.product_documents;
drop policy if exists "Enable admin full access to product documents" on public.product_documents;

create policy "Enable public read access on product case studies"
on public.product_case_studies for select
using (is_published = true);

create policy "Enable admin full access to product case studies"
on public.product_case_studies for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

create policy "Enable public read access on product documents"
on public.product_documents for select
using (is_published = true);

create policy "Enable admin full access to product documents"
on public.product_documents for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

insert into public.product_case_studies (
    slug, title, category, summary, role, timeline, mode, visual,
    context, problem, insight, approach, output, outcome, deliverables, sort_order, is_published
) values
(
    'apta-sounding',
    'Apta Sounding',
    'Operational Workflow',
    'Improving how field operators capture, validate, and prepare tank sounding data for follow-up.',
    'Product Thinker, UI/UX, Frontend Lead',
    'Real Product Study',
    'Learning & Next Improvement',
    'SOUNDING',
    'A field-operation product for recording tank sounding activity in palm oil manufacturing, where teams need reliable data even when connectivity and field conditions are not ideal.',
    'Operators must record accurate sounding values in the field, while supervisors need clean, traceable records for validation, correction, and follow-up.',
    'The highest-risk moment is not only data input. It is whether users understand incomplete records, bottom-only entries, and sync readiness before the data moves forward.',
    'Mapped the field workflow, separated operator intent from system state, and prioritized validation rules that protect data quality without blocking legitimate field work.',
    'A clearer input flow, local-save behavior, sync-preflight logic, and documented edge cases for incomplete or partial records.',
    'Operational products need explicit state design. The next validation should compare task completion time, error rate, and correction frequency before and after the revised flow.',
    array['Workflow Map', 'Validation Rules', 'User Flow', 'Edge Case Notes'],
    1,
    true
),
(
    'sraya-asset-workflow',
    'SRAYA Asset Workflow',
    'Enterprise Tool',
    'Structuring asset rental and repair workflows so users understand status, ownership, and next action.',
    'Frontend Lead, UI/UX, Product Analysis',
    'Real Product Study',
    'Learning & Next Improvement',
    'SRAYA',
    'An internal enterprise workflow product for managing asset data, rental status, repair records, and operational updates across teams.',
    'Complex asset states can confuse users when they need to know what can be edited, moved, repaired, activated, or handed off to another team.',
    'Operational users need predictable state transitions more than decorative UI. The interface should make the next valid action obvious.',
    'Reviewed workflow boundaries, aligned interface states with backend contracts, and framed each screen around action clarity and data consistency.',
    'Cleaner form behavior, consistent edit flows, date-handling rules, and action states that reduce ambiguity during operational handoff.',
    'Enterprise PM work often starts with state modeling. The next validation should test the most frequent rental and repair tasks with actual stakeholders.',
    array['State Mapping', 'Feature Spec', 'Acceptance Criteria', 'Flow Review'],
    2,
    true
),
(
    'lexora-learning-product',
    'Lexora Learning Product',
    'Education Product',
    'Designing a structured English and TOEFL learning product with curriculum clarity and visible progress.',
    'Product Strategy, Curriculum Planning, UI/UX',
    'Concept Product Study',
    'Validation Outcome',
    'LEXORA',
    'A learning product concept for structured English and TOEFL preparation, combining a fixed curriculum with adaptive remedial support.',
    'Self-learning loses momentum when lessons, progress, weak areas, and next actions are not visible across a long learning period.',
    'The core challenge is not only delivering content. Learners need to understand where they are, what they struggle with, and what to do next.',
    'Defined curriculum stages, mapped admin and student needs, separated fixed learning paths from remedial moments, and planned progress visibility.',
    'A learning journey structure, role distinction, curriculum scope, progress model, and quiz attempt flow.',
    'Concept validation should test whether learners understand the path, progress, and next action faster than in an unstructured flow. Next validation: lesson discovery, quiz submission, and progress interpretation.',
    array['Journey Map', 'Curriculum Scope', 'Progress Model', 'Validation Plan'],
    3,
    true
)
on conflict (slug) do update set
    title = excluded.title,
    category = excluded.category,
    summary = excluded.summary,
    role = excluded.role,
    timeline = excluded.timeline,
    mode = excluded.mode,
    visual = excluded.visual,
    context = excluded.context,
    problem = excluded.problem,
    insight = excluded.insight,
    approach = excluded.approach,
    output = excluded.output,
    outcome = excluded.outcome,
    deliverables = excluded.deliverables,
    sort_order = excluded.sort_order,
    is_published = excluded.is_published;

insert into public.product_documents (title, type, description, sort_order, is_published) values
('Mission 1 Intermediate', 'Foundation', 'Foundation work covering product observation, user context, and structured problem analysis.', 1, true),
('Mission 2', 'Practice', 'Product analysis practice focused on turning findings into clearer recommendations.', 2, true),
('Mission 2 Intermediate', 'Intermediate', 'Intermediate mission covering research synthesis, problem framing, and documentation structure.', 3, true),
('Mission 3', 'Practice', 'Practice work for mapping user flow, defining requirements, and clarifying solution direction.', 4, true),
('Mission 4', 'Practice', 'Product documentation exercise covering scope, user story, and acceptance criteria.', 5, true),
('Mission 5', 'Practice', 'Validation-focused mission for packaging decisions, test scenarios, and iteration notes.', 6, true),
('Mission Advanced', 'Advanced', 'Advanced work consolidating research, requirements, solution direction, and validation learning.', 7, true)
on conflict do nothing;

insert into storage.buckets (id, name, public)
values ('portfolio-assets', 'portfolio-assets', true)
on conflict (id) do update set public = true;
